/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author sachee
 */
public class checkinCounter extends javax.swing.JFrame {

    String ClassID;
    String monthcode;
    String firstDate;
    String payDate1;
    String payDate2;
    String payDate3;
    String payDate4;
    int fee;
    int balance;
    String Grade;
    Date dNow = new Date();
    SimpleDateFormat ftt
            = new SimpleDateFormat("yyyy-MM-dd");
    
    boolean b1 = false;

    /**
     * Creates new form payCounter
     */
    public checkinCounter(String ClassID, String monthcode,String firstDate,String payDate1,String payDate2,String payDate3,String payDate4) {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setSize(677, 250);
        jPanel1.setSize(677, 250);
        numberf.requestFocus();
        this.ClassID = ClassID;
        this.monthcode = monthcode;
        this.firstDate=firstDate;
        this.payDate1=payDate1;
        this.payDate2=payDate2;
        this.payDate3=payDate3;
        this.payDate4=payDate4;        
        searchm();
     
    }

    public void searchm() {

        String sql = "Select * From Class where ClassID like '" + ClassID + "'";

        try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException e) {
            System.out.println("mysql-java Drvier not found..");
        }
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/tution", "root", "1234");
            java.sql.Statement stm = conn.createStatement();
            ResultSet rst = stm.executeQuery(sql);
            rst.next();
            techrl.setText("  " + rst.getString("Teacher"));
            subl.setText("  " + rst.getString("Subject"));
            gradel.setText("  " + rst.getString("Grade"));
            Grade = rst.getString("Grade");
            timel.setText("  " + rst.getString("TimeStart") + "-" + rst.getString("TimeEnd"));
            feel.setText("  " + "Rs." + rst.getString("Fee"));
            fee = Integer.parseInt(rst.getString("Fee"));

        } catch (SQLException e) {
            System.out.println(e.getMessage());

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        numberf = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        timel = new javax.swing.JLabel();
        techrl = new javax.swing.JLabel();
        subl = new javax.swing.JLabel();
        gradel = new javax.swing.JLabel();
        feel = new javax.swing.JLabel();
        jToggleButton2 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numberf.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        numberf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                numberfKeyReleased(evt);
            }
        });
        jPanel1.add(numberf, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 640, 40));

        jToggleButton1.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tempico.png"))); // NOI18N
        jToggleButton1.setText("Temporary");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, 28));

        jLabel2.setText("Number");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 110, -1, -1));

        timel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        timel.setForeground(new java.awt.Color(102, 102, 102));
        timel.setText("13.00-15.00");
        timel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.add(timel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 71, 330, -1));

        techrl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        techrl.setForeground(new java.awt.Color(102, 102, 102));
        techrl.setText("Sunil Kamal Nimal");
        techrl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.add(techrl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 9, 645, -1));

        subl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        subl.setForeground(new java.awt.Color(102, 102, 102));
        subl.setText("Maths");
        subl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.add(subl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 330, -1));

        gradel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        gradel.setForeground(new java.awt.Color(102, 102, 102));
        gradel.setText("Grade10");
        gradel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.add(gradel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 315, -1));

        feel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        feel.setForeground(new java.awt.Color(102, 102, 102));
        feel.setText("Rs.400");
        feel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.add(feel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 71, 315, -1));

        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Entypo_2328(0)_32.png"))); // NOI18N
        jToggleButton2.setText("Auto");
        jPanel1.add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 180, 100, 28));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, 677, 220));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public boolean stusearch() {
        boolean b = false;
        String sql = "Select * From Attendance where IsPayed like 'Yes' and MonthCode like '" + monthcode + "' and ClassID like '" + ClassID + "'";

        try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException e) {
            System.out.println("mysql-java Drvier not found..");
        }
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/tution", "root", "1234");
            java.sql.Statement stm = conn.createStatement();
            ResultSet rst = stm.executeQuery(sql);

            for (int i = 0; rst.next(); i++) {
                if (rst.getString(1).equals(numberf.getText())) {
                    b = true;
                }
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        return b;
    }

       public boolean stusearchID() {
        boolean b = false;
        String sql = "Select StID From Student";

        try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException e) {
            System.out.println("mysql-java Drvier not found..");
        }
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/tution", "root", "1234");
            java.sql.Statement stm = conn.createStatement();
            ResultSet rst = stm.executeQuery(sql);

            for (int i = 0; rst.next(); i++) {
                if (rst.getString(1).equals(numberf.getText())) {
                    b = true;
                }
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        return b;
    }
//    public String searchByGrade() {
//        String sql = "Select StID,Name From student where Grade like '" + Grade + "'";
//        String stname = "";
//        try {
//            Class.forName("com.mysql.jdbc.Driver");
//        } catch (ClassNotFoundException e) {
//            System.out.println("mysql-java Drvier not found..");
//        }
//        try {
//            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/tution", "root", "1234");
//            java.sql.Statement stm = conn.createStatement();
//            ResultSet rst = stm.executeQuery(sql);
//
//            for (int i = 0; rst.next(); i++) {
//                if (rst.getString(1).equals(numberf.getText())) {
//                    stname = rst.getString(2);
//                }
//            }
//        } catch (SQLException e) {
//            System.out.println(e.getMessage());
//        }
//        return stname;
//    }

    public void setCheck(){
         if(ftt.format(dNow).equals(payDate1) || ftt.format(dNow).equals(payDate2) || ftt.format(dNow).equals(payDate3) || ftt.format(dNow).equals(payDate4)) {
                if(stusearch()==false){
                    JOptionPane.showMessageDialog(null, "Not paid", "ERROR", JOptionPane.ERROR_MESSAGE);
                    
                }
            else{
                 try {
                Class.forName("com.mysql.jdbc.Driver");
            } catch (ClassNotFoundException e) {
                System.out.println("mysql-java Drvier not found..");
            }
            try {
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/tution", "root", "1234");
               java.sql.Statement stm = conn.createStatement();
                String sql1 = "UPDATE Attendance SET Date1='PRESENT' WHERE StID='"+numberf.getText()+
                        "' and IsPayed like 'Yes' and MonthCode like '" + monthcode + "' and ClassID like '" + ClassID + "'";
                String sql2 = "UPDATE Attendance SET Date2='PRESENT' WHERE StID='"+numberf.getText()+
                        "' and IsPayed like 'Yes' and MonthCode like '" + monthcode + "' and ClassID like '" + ClassID + "'";
                String sql3 = "UPDATE Attendance SET Date3='PRESENT' WHERE StID='"+numberf.getText()+
                        "' and IsPayed like 'Yes' and MonthCode like '" + monthcode + "' and ClassID like '" + ClassID + "'";
                String sql4 = "UPDATE Attendance SET Date4='PRESENT' WHERE StID='"+numberf.getText()+
                        "' and IsPayed like 'Yes' and MonthCode like '" + monthcode + "' and ClassID like '" + ClassID + "'";
                String sql5 = "UPDATE Attendance SET Date5='PRESENT' WHERE StID='"+numberf.getText()+
                        "' and IsPayed like 'Yes' and MonthCode like '" + monthcode + "' and ClassID like '" + ClassID + "'";

                if(ftt.format(dNow).equals(payDate1))stm.executeUpdate(sql2);
                if(ftt.format(dNow).equals(payDate2))stm.executeUpdate(sql3);
                if(ftt.format(dNow).equals(payDate3))stm.executeUpdate(sql4);
                if(ftt.format(dNow).equals(payDate4))stm.executeUpdate(sql5);
                
     
            } catch (SQLException e) {
                System.out.println(e.getMessage());
            }
            }
        }
//            System.out.println(ftt.format(dNow));
//            System.out.println(firstDate);
//            System.out.println(ftt.format(dNow).equals(firstDate));
           if(ftt.format(dNow).equals(firstDate) && (stusearchID() == false  ) ){
               if(jToggleButton1.isSelected()){
               if(stusearch()==false){
                   String sql1 = "Insert into Attendance Values(?,?,?,?,?,?,?,?,?,?,?,?,?,?)";

                try {
                    Class.forName("com.mysql.jdbc.Driver");
                } catch (ClassNotFoundException e) {
                    System.out.println("mysql-java Drvier not found..");
                }
                try {
                    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/tution", "root", "1234");
                    PreparedStatement stm = conn.prepareStatement(sql1);

                   stm.setObject(1, numberf.getText());
                    stm.setObject(2, ClassID);
                    stm.setObject(3, monthcode);
                    stm.setObject(4, "No");
                    stm.setObject(5, "");
                    stm.setObject(6, "");
                    stm.setObject(7, "");
                    stm.setObject(8, jToggleButton1.isSelected() ? "Yes" : "");
                    stm.setObject(9, "");
                    stm.setObject(10, "PRESENT");
                    stm.setObject(11, "");
                    stm.setObject(12, "");
                    stm.setObject(13, "");
                    stm.setObject(14, "");
                    stm.executeUpdate();

                    

                } catch (SQLException e) {
                    System.out.println(e.getMessage());
                }
                   
                }else{ 
                   try {
                Class.forName("com.mysql.jdbc.Driver");
            } catch (ClassNotFoundException e) {
                System.out.println("mysql-java Drvier not found..");
            }
            try {
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/tution", "root", "1234");
               java.sql.Statement stm = conn.createStatement();
                String sql = "UPDATE Attendance SET Date1='PRESENT' WHERE StID='"+numberf.getText()+
                        "' and IsPayed like 'Yes' and MonthCode like '" + monthcode + "' and ClassID like '" + ClassID + "'";

                stm.executeUpdate(sql);
        
            } catch (SQLException e) {
                System.out.println(e.getMessage());
            }
               }
           }else{
            JOptionPane.showMessageDialog(null, "Temporary student", "ERROR", JOptionPane.ERROR_MESSAGE);
            jToggleButton1.setSelected(true);
        }
           }
           
           numberf.setText("");
    }
    
    private void numberfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numberfKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_0
                || evt.getKeyCode() == KeyEvent.VK_1
                || evt.getKeyCode() == KeyEvent.VK_2
                || evt.getKeyCode() == KeyEvent.VK_3
                || evt.getKeyCode() == KeyEvent.VK_4
                || evt.getKeyCode() == KeyEvent.VK_5
                || evt.getKeyCode() == KeyEvent.VK_6
                || evt.getKeyCode() == KeyEvent.VK_7
                || evt.getKeyCode() == KeyEvent.VK_8
                || evt.getKeyCode() == KeyEvent.VK_9
                || evt.getKeyCode() == KeyEvent.VK_NUMPAD0
                || evt.getKeyCode() == KeyEvent.VK_NUMPAD1
                || evt.getKeyCode() == KeyEvent.VK_NUMPAD2
                || evt.getKeyCode() == KeyEvent.VK_NUMPAD3
                || evt.getKeyCode() == KeyEvent.VK_NUMPAD4
                || evt.getKeyCode() == KeyEvent.VK_NUMPAD5
                || evt.getKeyCode() == KeyEvent.VK_NUMPAD6
                || evt.getKeyCode() == KeyEvent.VK_NUMPAD7
                || evt.getKeyCode() == KeyEvent.VK_NUMPAD8
                || evt.getKeyCode() == KeyEvent.VK_NUMPAD9) {
            int c = 0;
            String numbers = numberf.getText();
            c = numbers.length();
            if (c >= 10 && jToggleButton2.isSelected()) {
                setCheck();
            }
        }
        if (evt.getKeyCode() == KeyEvent.VK_ENTER && !jToggleButton2.isSelected()) {
           setCheck();
        }
        if (evt.getKeyCode() == KeyEvent.VK_PAGE_DOWN) {
            int n = 10 - numberf.getText().length();
            for (int i = 0; i < n; i++) {
                numberf.setText("0" + numberf.getText());
            }
        }
    }//GEN-LAST:event_numberfKeyReleased

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(checkinCounter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(checkinCounter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(checkinCounter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(checkinCounter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new checkinCounter("C1", "c12016january","c12016january","2016-07-31","2016-07-31","2016-07-31","2016-07-31").setVisible(true);
            }
        });
    }
    javax.swing.table.DefaultTableModel mod;
    javax.swing.table.DefaultTableModel mod2;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel feel;
    private javax.swing.JLabel gradel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JTextField numberf;
    private javax.swing.JLabel subl;
    private javax.swing.JLabel techrl;
    private javax.swing.JLabel timel;
    // End of variables declaration//GEN-END:variables
}
