/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.freeHalfController;
import controller.otherController;
import controller.studentController;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import model.comboModel;
import model.studentModel;

/**
 *
 * @author sachee
 */
public class freeHalf extends javax.swing.JFrame {

    String ClassID;

    /**
     * Creates new form freeHalf
     */
    public freeHalf(String ClassID) {
        initComponents();
        setLocationRelativeTo(null);
        this.ClassID = ClassID;
        searchm2();
        initialize();
    }

    public void initialize() {
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/stuicofree.png")));
        jTextField1.requestFocus();
        setTitle("Half and free card manage form");
    }
    
    public void searchm2() {
        mod.setRowCount(0);
        mod2.setRowCount(0);
        try {
            studentModel[] clsM = controller.freeHalfController.viewStudentFree(ClassID);
            studentModel[] clsM2 = controller.freeHalfController.viewStudentHalf(ClassID);

            for (int i = 0; i < clsM.length; i++) {
                String rowmod[] = {clsM[i].getStID(), clsM[i].getName(), clsM[i].getAddress(), clsM[i].getSchool(), clsM[i].getTelM() + "/" + clsM[i].getTelH()};
                mod.addRow(rowmod);
            }

            for (int i = 0; i < clsM2.length; i++) {
                String rowmod[] = {clsM2[i].getStID(), clsM2[i].getName(), clsM2[i].getAddress(), clsM2[i].getSchool(), clsM2[i].getTelM() + "/" + clsM2[i].getTelH()};
                mod2.addRow(rowmod);
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(freeHalf.this, ex.getMessage());
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(freeHalf.this, ex.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(599, 0, 1, 560));

        jTable2.setModel(mod2=new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Number", "Name", "Address", "School", "Telephone"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, 580, 390));

        jTable3.setModel(mod=new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Number", "Name", "Address", "School", "Telephone"
            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 580, 390));

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 530, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/addstu.png"))); // NOI18N
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 68, 40, -1));

        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, 530, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/addstu.png"))); // NOI18N
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 70, 40, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Half");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, 80, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Free");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 80, 20));

        jButton3.setText("Remove");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 500, -1, -1));

        jButton4.setText("Remove");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 500, -1, -1));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Entypo_e75d(0)_28.png"))); // NOI18N
        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1105, 10, -1, 23));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            boolean isAdded = freeHalfController.addNameFree(ClassID, jTextField1.getText());

            if (isAdded) {
                jTextField1.setText("");
                searchm2();
            } else {
                JOptionPane.showMessageDialog(freeHalf.this, "Adding failed");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(freeHalf.this, ex.getMessage());
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(freeHalf.this, ex.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        try {
            boolean isAdded = freeHalfController.addNameHalf(ClassID, jTextField2.getText());

            if (isAdded) {
                jTextField2.setText("");
                searchm2();
            } else {
                JOptionPane.showMessageDialog(freeHalf.this, "Adding failed");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(freeHalf.this, ex.getMessage());
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(freeHalf.this, ex.getMessage());
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_PAGE_DOWN) {
            int n = 10 - jTextField1.getText().length();
            for (int i = 0; i < n; i++) {
                jTextField1.setText("0" + jTextField1.getText());
            }

        }

        if (evt.getKeyCode() == KeyEvent.VK_ENTER && !jTextField1.getText().isEmpty()) {
            try {
                boolean isAdded = freeHalfController.addNameFree(ClassID, jTextField1.getText());

                if (isAdded) {
                    jTextField1.setText("");
                    searchm2();
                } else {
                    JOptionPane.showMessageDialog(freeHalf.this, "Adding failed");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(freeHalf.this, ex.getMessage());
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(freeHalf.this, ex.getMessage());
            }
        }

        if (!jTextField1.getText().isEmpty()) {
            jButton1.setEnabled(true);
        } else {
            jButton1.setEnabled(false);
        }
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_PAGE_DOWN) {
            int n = 10 - jTextField2.getText().length();
            for (int i = 0; i < n; i++) {
                jTextField2.setText("0" + jTextField2.getText());
            }

        }

        if (evt.getKeyCode() == KeyEvent.VK_ENTER && !jTextField2.getText().isEmpty()) {
            try {
                boolean isAdded = freeHalfController.addNameHalf(ClassID, jTextField2.getText());

                if (isAdded) {
                    jTextField2.setText("");
                    searchm2();
                } else {
                    JOptionPane.showMessageDialog(freeHalf.this, "Adding failed");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(freeHalf.this, ex.getMessage());
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(freeHalf.this, ex.getMessage());
            }
        }

        if (!jTextField2.getText().isEmpty()) {
            jButton2.setEnabled(true);
        } else {
            jButton2.setEnabled(false);
        }
    }//GEN-LAST:event_jTextField2KeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        final int index = jTable3.getSelectedRow();
        String conumber;
        if (index >= 0) {
            conumber = (String) jTable3.getValueAt(index, 0);

            try {
                boolean isAdded = freeHalfController.deleteName(ClassID, conumber);
                if (isAdded) {
                    JOptionPane.showMessageDialog(freeHalf.this, "Record deleted successfully");
                    searchm2();
                } else {
                    JOptionPane.showMessageDialog(freeHalf.this, "Record deleting failed");

                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(freeHalf.this, ex.getMessage());
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(freeHalf.this, ex.getMessage());
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked

        
        
    }//GEN-LAST:event_jTable3MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        final int index = jTable2.getSelectedRow();
        String conumber;
        if (index >= 0) {
            conumber = (String) jTable2.getValueAt(index, 0);

            try {
                boolean isAdded = freeHalfController.deleteName(ClassID, conumber);
                if (isAdded) {
                    JOptionPane.showMessageDialog(freeHalf.this, "Record deleted successfully");
                    searchm2();
                } else {
                    JOptionPane.showMessageDialog(freeHalf.this, "Record deleting failed");

                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(freeHalf.this, ex.getMessage());
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(freeHalf.this, ex.getMessage());
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new viewClassFreeHalf().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(freeHalf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(freeHalf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(freeHalf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(freeHalf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    javax.swing.table.DefaultTableModel mod;
    javax.swing.table.DefaultTableModel mod2;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
